### ISSUE TITLE
Failed to compile Project.sln

### ISSUE THREAD

**Issue by jfaz13** [onehundredfeet/hashlink-bullet#9]
Hello,

Trying to compile Project.sln generates the following errors:
![image](https://user-images.githubusercontent.com/25165780/133486170-e103b186-49a2-481e-967a-942c0da3f3f9.png)

At first I thought it was that I was using VS2019 so I tried again with VS2017 with the same issue. Then I tried using the release build of Bullet3 instead of the latest commit, also nothing different. I generate the build files using the following command in the VS dev console:
`cmake .. -A x64 -G "Visual Studio 16 2019" -DBULLET_SRC_DIR="bullet3/src" -DHL_INCLUDE_DIR="C:\Libraries\hl\include" -DHL_LIB_DIR="C:\Libraries\hl\" -HDLL_DESTINATION="C:\Libraries\hl\"`

I also tried building for different targets (debug/release) and projects (INSTALL/ALL_BUILD) and I get the same error on all except for ZERO_CHECK.

Any help is appreciated!

**Comment by onehundredfeet** [comment]
I'm using cmake w/ ninja and I'm getting a different error on windows.  I'll figure it out and get back to you.

**Comment by onehundredfeet** [comment]
may want to try again with the latest hl-idl

**Comment by onehundredfeet** [comment]
It was a macro bug.

I added:

#undef min
#undef max

Before including the bullet headers and it works.
